server:
  port: 8088

## URL Rest Services applicacion
coins:
  baseURL: 'api/coins'
  healthAPI: '/health-api'
  derivativesApi: '/derivatives'
  derivativesExchangesApi: '/derivatives/exchanges'

## Url Coin Gecko RestService
api:
  urlCoinGecko: 'https://api.coingecko.com/api/v3'
  ping: '/ping'
  derivativesGecko: '/derivatives'
  derivativesExchangesGecko: '/derivatives/exchanges'
